### PR TITLE
update dependencies and fix cypress coverage

### PR DESCRIPTION
**Pull request by scytacki**
- dependencies updated with npm update
- node-sass updated to version 7
  this was needed to remove npm audit issue with caused by old regex depencency
- svgr/webpack was updated to version 6 this removed another npm audit issue
  there are no SVGs in this repo so I'm not sure if this upgrade requires additional
  changes to webpack.config.js
- istanbul-instrumenter-loader was replaced with coverage-istanbul-loader
  the old dependency was no longer supported, and seemed to not be compatible with
  webpack 5.
- cypress code coverage was added back to cypress/plugins/index.js, this was
  accidentally removed here: https://github.com/concord-consortium/starter-projects/pull/45/files
- cypress coverage tasks are disabled by default now so they don't clutter up the
  log when running cypress tests, see cypress.json
- cypress coverage is enabled in github actions ci.yml file, and with new npm script
  test:coverage:cypress:open
- .eslintrc.js was updated to enforce single quotes and dangling commas in webpack.config.js

### CODE REVIEW

**Comment by scytacki** [comment]
node-sass says it needed node version 17, but on github actions this seems to be running on node 16 and it worked fine.

**Review by kswenson — CHANGES_REQUESTED** [review]
👍 Mostly looks good -- I have two suggestions:
1. try replacing `node-sass` with `sass` (which is the pure JavaScript implementation). On the handful of projects I've tried it on it's been a drop-in replacement and it doesn't have any of the complicated node version requirements of `node-sass`.
2. @svgr/webpack 6 changes the configuration format -- you can take the updated configuration from DESE.
3. I would vote against the commas, but I don't feel that strongly about it if you feel otherwise.

Also, I can do those things if you want since it's earlier in my day than it is in yours.

**Comment by scytacki** [comment]
OK I think I addressed all 3 comment.
I removed the comma-dangle lint rule. I left many of the commas though. My internal rule was to add them to multiline arrays and objects except then the last line of the last item ended with a `}` or `]`. This way any real content has a dangling common so changes after it won't cause extra lines in the diff.

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Pull request merged**
