### PR TITLE
support configured buckets, and root of bucket deploys

### PR DESCRIPTION
**Pull request by scytacki**
These changes are necessary to support the portal-report repository. 
I think we also have some other legacy repositories that deploy to the root of a custom bucket.

### CODE REVIEW

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Comment by scytacki** [comment]
I just switched it back to a draft because my attempt to use it with the portal-report is taking forever:
https://github.com/concord-consortium/portal-report/pull/259/checks?check_run_id=1432902624
Which most likely means the 'ignore_on_server' param isn't working and s3_website is looking for file changes in every single file in the bucket.

**Comment by scytacki** [comment]
Successful build using this config here:
https://github.com/concord-consortium/portal-report/runs/1433380978?check_suite_focus=true#step:7:24

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Pull request merged**
