### PR TITLE
Add ability to run securely using HTTPS to starter projects

### PR DESCRIPTION
**Pull request by mklewandowski**
UPDATE:
The latest commit uses `webpack-config.js` to specify the key/cert files in both the Windows and Mac home directory as follows:
```
      https: {
        key: fs.readFileSync(path.resolve(os.homedir(), '.localhost-ssl/localhost.key')),
        cert: fs.readFileSync(path.resolve(os.homedir(), '.localhost-ssl/localhost.pem')),
      },
```

Using `webpack-dev-server` version 4.0 beta we can then use this in conjunction with the new option `--no-https`  to turn off the HTTPS that we configure in  `webpack-config.js`  when we want to run simple HTTP.  

This is probably the most simplistic solution that requires a single system change for both Mac and Windows users (and once it is done for one project, it should work for others).  However, this does mean waiting for `webpack-dev-server` version 4 to be published before we can finalize and merge this branch.

ORIGINAL COMMENT:
There might be a cleaner solution here so for now, I'm putting this PR into draft.  This solution requires the user to create or copy the cert and key file into the project folder of each project that the user wants to run locally using HTTPS.  So this change would require action on a per project basis rather than a single action that happens once on the system.  

That said, if we look at, for example, the implementation that currently exists in the Activity Player, we have the following script in `package.json`:

`"start:secure": "webpack-dev-server --https --inline --hot --content-base dist/ --cert ~/.localhost-ssl/localhost.pem --key ~/.localhost-ssl/localhost.key",`

I didn't fire up a Mac and test, but I'm assuming this allows the user to create a single folder containing the key and cert files in the home directory.  However using ~ to access the home directory doesn't work on Windows.  So even though the above presumably allows for a system-wide solution on Mac, it causes failure on Windows.  We *could* leave the above and have a second Windows specific script (`start:secure:windows` or something) that requires the user to add the cert and key file to the project ONLY when using Windows.  This is a bit more convoluted, but at least most of our devs (who are on Macs) would have a straightforward solution that would be easier to apply to all projects.  Maybe I'm missing something obvious or a better Windows handling?  I'm open to thoughts on this.

### CODE REVIEW

**Comment by scytacki** [comment]
You can put the params in in the webpack conf file like this:
https://webpack.js.org/configuration/dev-server/#devserverhttps

Then you can use node.js functions to find the home directory, or you could use a different directory on windows if that is better.

**Comment by mklewandowski** [comment]
> You can put the params in in the webpack conf file like this:
> https://webpack.js.org/configuration/dev-server/#devserverhttps
> 
> Then you can use node.js functions to find the home directory, or you could use a different directory on windows if that is better.

Adding this to webpack-config.js gets us to the "home" directory on modern Windows machines (the user directory) and presumably works on Mac machines as well:
```
      https: {
        key: fs.readFileSync(path.resolve(os.homedir(), '.localhost-ssl/localhost.key')),
        cert: fs.readFileSync(path.resolve(os.homedir(), '.localhost-ssl/localhost.pem')),
      },
```
However, this forces us to run https every time we run `webpack serve`.  So even `npm start` will run at https://localhost:8080/.  So this works, but I'm not sure how we can tell it to only use https sometimes.  At first glance, that's the advantage to setting this up with multiple script entries in package.json.

**Comment by mklewandowski** [comment]
@scytacki the other simple route is to just add a new script and instructions for Windows users only.  So we would have:
```
    "start:secure": "webpack-dev-server --https --inline --hot --content-base dist/ --cert ~/.localhost-ssl/localhost.pem --key ~/.localhost-ssl/localhost.key",
    "start:secure-windows": "webpack serve --https --inline --hot --content-base dist/ --cert ./.localhost-ssl/localhost.pem --key ./.localhost-ssl/localhost.key",
```
First script behaves exactly as we have it implemented in other projects.  Second script is for Windows users (which seems to be rare at this org) and requires making a local folder in the project and copying the certs into it.

**Comment by kswenson** [comment]
What about writing a small node.js script that could use the `path.resolve(os.homedir(), '.localhost-ssl/localhost.pem')` approach and then launch the webpack dev server with the result? Wouldn't that make it possible to have a cross-platform approach that would work for Windows and Mac/*nix?

**Comment by mklewandowski** [comment]
> What about writing a small node.js script that could use the `path.resolve(os.homedir(), '.localhost-ssl/localhost.pem')` approach and then launch the webpack dev server with the result? Wouldn't that make it possible to have a cross-platform approach that would work for Windows and Mac/*nix?

That could work.  Not sure exactly how to do that, but I can look into it.

**Comment by scytacki** [comment]
@mklewandowski did you try overriding the https with a parameter `--no-https`? 
It is referred to here:
https://github.com/webpack/webpack-dev-server
Which is different than what we are using which is documented here:
https://github.com/webpack/webpack-cli/blob/master/SERVE-OPTIONS.md

But hopefully it works anyhow.

If we can avoid different windows and unix scripts that would be nice so we don't have to have separate windows sections in the readme. So if the `--no-https` option doesn't work, then I'd vote for Kirk's script approach.

**Comment by mklewandowski** [comment]
> @mklewandowski did you try overriding the https with a parameter `--no-https`?
> It is referred to here:
> https://github.com/webpack/webpack-dev-server
> Which is different than what we are using which is documented here:
> https://github.com/webpack/webpack-cli/blob/master/SERVE-OPTIONS.md
> 
> But hopefully it works anyhow.
> 
> If we can avoid different windows and unix scripts that would be nice so we don't have to have separate windows sections in the readme. So if the `--no-https` option doesn't work, then I'd vote for Kirk's script approach.

Hmm... I'm fairly lost at this point.  I can't even get `webpack-dev-server` to work in the starter projects.  It just throws an error:
`Error: Cannot find module 'webpack-cli/bin/config-yargs'`
So maybe it's not compatible with the webpack 5?  Have we tested this?  I see the Activity Player is still in webpack 4 and it successfully uses `webpack-dev-server`.

**Comment by mklewandowski** [comment]
> config-yargs

Yeah, config-yargs is gone in webpack 5.  That file doesn't exist.  So I'm assuming webpack-dev-server is not compatible with webpack 5?  That seems odd.

**Review by scytacki — APPROVED** [review]
Looks great to me. I hope webpack-dev-server comes out of beta soon.

**Review by kswenson — APPROVED** [review]
👍 Looks good

**Comment by scytacki** [comment]
Looks like webpack-dev-server 4.0 came out about a month ago. It has gone through a few releases since then. 

Anyone care to try updating the PR?

**Comment by mklewandowski** [comment]
> Looks like webpack-dev-server 4.0 came out about a month ago. It has gone through a few releases since then.
> 
> Anyone care to try updating the PR?

Yup, I'll take a look and see if we can get this in.

**Comment by mklewandowski** [comment]
> > Looks like webpack-dev-server 4.0 came out about a month ago. It has gone through a few releases since then.
> > Anyone care to try updating the PR?
> 
> Yup, I'll take a look and see if we can get this in.

@kswenson @scytacki Looks to work!  I'm able to run http and https locally with the updated webpack-dev-server.

**Review by kswenson — APPROVED** [review]
👍  LGTM

**Pull request merged**
