### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mklewandowski**
A quick PR to update dependencies.  This PR only updates minor/patch versions and doesn't include major version updates.  I'm open to major version updates as well if people have thoughts on the matter and have made the updates in other projects.

EDIT: I upgraded all dependencies to the latest version with the exception of: autoprefixer, copy-webpack-plugin, css-loader, webpack, webpack-cli.
I also added svgr to improve the use of SVG files within React components.

### CODE REVIEW

**Review by scytacki — APPROVED** [review]
Looks good to me.
Major version updates would be better, but any minor version update is better than letting this project be stale.

**Review by kswenson — CHANGES_REQUESTED** [review]
👍 Looks fine as far as it goes, but I'd recommend doing the major upgrades as well and only backing off if you run into problems. I've done Cypress 5, TypeScript 4, etc. on other projects and they haven't presented serious issues. css-loader 4 requires an updated configuration if you're using css modules or importing values from .scss files into TypeScript, but the configuration change is straightforward. I haven't tried Webpack 5 yet but I think it'd be an interesting experiment. I'd also add the @svgr icon importer if it's not already included.

**Review by pjanik — APPROVED** [review]

**Comment by mklewandowski** [comment]
@kswenson I updated almost all of the dependencies that required major version upgrades except a few that gave me trouble webpack specific packages (I wanted to wait while Scott continued looking at webpack 5).  Everything builds, runs, and unit/integration tests pass.  I also set up svgr so we have an easier path to import SVG files (I tested this locally by adding an SVG and importing and displaying it in a React component).  I'm also going to upgrade to eslint in a separate PR.

**Review by kswenson — APPROVED** [review]
👍 Looks good -- you might just add a comment to the PR description about which modules were not updated to latest major versions, e.g. css-modules and Webpack. ~~Also, there should be a story somewhere for switching from TSLint => ESLint.~~ I see you already mentioned that above. 😉

**Comment by mklewandowski** [comment]
@kswenson I updated the PR description and added a general starter project upgrade story that encompasses this work and the move from tslint to eslint that I'm working on now.

**Pull request merged**
